# frozen_string_literal: true

source "https://rubygems.org"

# During development these resolve against the local monorepo build. The release
# sync (release/targets/60-var-examples.sh) rewrites them to the published
# versions, e.g. gem "varar-minitest", "~> 0.3".
gem "varar-core", path: "../../ruby/packages/var-core"
gem "varar", path: "../../ruby/packages/var"
gem "varar-config", path: "../../ruby/packages/var-config"
gem "varar-runner", path: "../../ruby/packages/var-runner"
gem "varar-minitest", path: "../../ruby/packages/var-minitest"

gem "minitest", "~> 5.20"
gem "rake", "~> 13.0"
