// Fetches cucumber/gherkin's gherkin-languages.json from the official repo
// and emits packages/bdd/src/keywords-data.ts. Run on demand, not in CI.

import { writeFileSync } from 'node:fs'
import { resolve } from 'node:path'

const URL = 'https://raw.githubusercontent.com/cucumber/gherkin/main/gherkin-languages.json'

async function main() {
  const res = await fetch(URL)
  if (!res.ok) throw new Error(`fetch ${URL}: ${res.status}`)
  const data = (await res.json()) as Record<
    string,
    {
      name: string
      native: string
      given: ReadonlyArray<string>
      when: ReadonlyArray<string>
      then: ReadonlyArray<string>
      and: ReadonlyArray<string>
      but: ReadonlyArray<string>
    }
  >
  // Build a flat array of every keyword (trimmed, '* ' wildcard excluded).
  const set = new Set<string>()
  for (const lang of Object.values(data)) {
    for (const group of ['given', 'when', 'then', 'and', 'but'] as const) {
      for (const kw of lang[group]) {
        const trimmed = kw
          .trim()
          .replace(/[:\s]+$/, '')
          .trim()
        if (trimmed.length === 0) continue
        if (trimmed === '*') continue
        set.add(trimmed)
      }
    }
  }
  const sorted = [...set].sort()
  const out = `// AUTO-GENERATED by scripts/sync-keywords.ts. Do not edit by hand.\nexport const KEYWORDS: ReadonlyArray<string> = ${JSON.stringify(sorted, null, 2)}\n`
  const target = resolve(import.meta.dirname, '..', 'src', 'keywords-data.ts')
  writeFileSync(target, out)
  console.error(`wrote ${target} (${sorted.length} keywords)`)
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
